# Generated by Django 6.0 on 2025-12-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zootopia', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medication_amount',
        ),
        migrations.AddField(
            model_name='animalmedicationlog',
            name='medication_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
